name: Deploy Python Lambda

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Uses an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clones the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Set Python version to match Lambda runtime

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli  # Installs AWS CLI

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # AWS Region

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .  # Install dependencies into the current directory (if any)

      - name: Zip the Lambda function
        run: zip -r function.zip . -x "*.git*"  # Create a zip package for Lambda

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name CounterFunction \
            --zip-file fileb://lambdaauto.py  # Replace with your actual function name
