name: Deploy Python Lambda

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Uses an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clones the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Set Python version to match Lambda runtime

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .  # Install dependencies into the current directory (if any)

      - name: Zip the Lambda function
        run: zip -r lambdaauto.zip . -x "*.git*"  # Create a zip package for Lambda

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name CounterFunction \
            --zip-file fileb://lambdaauto.zip \
            --region us-east-1
