name: Deploy Python Lambda

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Uses an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clones the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Set Python version to match Lambda runtime

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .  # Install dependencies into the current directory (if any)

      - name: Zip the Lambda function
        run: |
          zip -r lambda_function_payload.zip lambda_function.py  # Zip only the Lambda function code
          # If you have additional files, include them in the zip command

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your AWS region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Use the latest stable version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve